name: Docker Publish

on:
  push:
    branches:
      - 'main'
#    tags:
#      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-image-tag: [3.11, 3.11-slim]
        poetry-version: [1.7.1]
    env:
      IMAGE_TAG: poetry${{ matrix.poetry-version }}-py${{ matrix.python-image-tag }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # https://github.com/docker/metadata-action
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ilyanekhay/poetry
          tags: |
            ${{ env.IMAGE_TAG }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            PYTHON_IMAGE_TAG=${{ matrix.python-image-tag }}
            POETRY_VERSION=${{ matrix.poetry-version }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ env.IMAGE_TAG }}
          cache-to: type=gha,mode=max,scope=${{ env.IMAGE_TAG }}
